baseurl = "https://example.com/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Cameron Morris"
title = "Cameron's castrum"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
copyright = "Copyright © 2017 Cameron Morris"
logofile = "img/logo.jpg"
faviconfile = "img/logo.jpg"
highlightjs = true
progressively = true
latestpostcount = 5
github = "zephyrz4"
email = "cameron.morris3@gmail.com"
linkedin = "cameron-morris-bb9b2733"
twitter = "zephyrz4"
social_banner = "img/banner.png"
posts_navigation = true

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
